// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace DisenchantMusicPlayer
{
    [default_interface]
    runtimeclass ArtistlistPage : Microsoft.UI.Xaml.Controls.Page
    {
        ArtistlistPage();
        Int32 MyProperty;
    }
}
