#pragma once
#include "SonglistItem.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.

namespace winrt::DisenchantMusicPlayer::implementation
{
    struct SonglistItem : SonglistItemT<SonglistItem>
    {
        // Step1: On the default constructor, change = default to = delete. That's because we don't want a default constructor.
        //SonglistItem() = default;
        SonglistItem() = delete;

        SonglistItem(hstring const& songName, hstring const& albumName, hstring const& coverPath);
        hstring SongName();
        void SongName(hstring const& value);
        hstring AlbumName();
        void AlbumName(hstring const& value);
        hstring CoverPath();
        void CoverPath(hstring const& value);
        winrt::event_token PropertyChanged(winrt::Windows::UI::Xaml::Data::PropertyChangedEventHandler const& handler);
        void PropertyChanged(winrt::event_token const& token) noexcept;

    private:
        // Step2: Add a private member to store the title string. Note that we have a constructor that takes a winrt::hstring value. That value is the title string.
        winrt::hstring m_songName;
        winrt::hstring m_albumName;
        winrt::hstring m_coverPath;

        // Step3: Add another private member for the event that we'll raise when the title changes.
        winrt::event<Windows::UI::Xaml::Data::PropertyChangedEventHandler> m_propertyChanged;

    };
}
namespace winrt::DisenchantMusicPlayer::factory_implementation
{
    struct SonglistItem : SonglistItemT<SonglistItem, implementation::SonglistItem>
    {
    };
}
