// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace DisenchantMusicPlayer
{
    [default_interface]
    runtimeclass SonglistPage : Microsoft.UI.Xaml.Controls.Page
    {
        SonglistPage();
        Int32 MyProperty;
    }
}
