//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::DisenchantMusicPlayer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainPageT : public ::winrt::DisenchantMusicPlayer::implementation::MainPage_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainPageT::base_type;
        using base_type::base_type;
        using class_type = typename MainPageT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid AppTitleBar()
        {
            return _AppTitleBar;
        }
        void AppTitleBar(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _AppTitleBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView RNav()
        {
            return _RNav;
        }
        void RNav(::winrt::Microsoft::UI::Xaml::Controls::NavigationView value)
        {
            _RNav = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Frame RNavContentFrame()
        {
            return _RNavContentFrame;
        }
        void RNavContentFrame(::winrt::Microsoft::UI::Xaml::Controls::Frame value)
        {
            _RNavContentFrame = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainPage_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _AppTitleBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView _RNav{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Frame _RNavContentFrame{nullptr};
    };
}

