//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::DisenchantMusicPlayer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct SettingsPageT : public ::winrt::DisenchantMusicPlayer::implementation::SettingsPage_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename SettingsPageT::base_type;
        using base_type::base_type;
        using class_type = typename SettingsPageT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Button PickFolderButton()
        {
            return _PickFolderButton;
        }
        void PickFolderButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _PickFolderButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock OutputTextBlock()
        {
            return _OutputTextBlock;
        }
        void OutputTextBlock(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _OutputTextBlock = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct SettingsPage_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Button _PickFolderButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _OutputTextBlock{nullptr};
    };
}

