// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_DisenchantMusicPlayer_SonglistItem()
{
    return winrt::detach_abi(winrt::make<winrt::DisenchantMusicPlayer::factory_implementation::SonglistItem>());
}
WINRT_EXPORT namespace winrt::DisenchantMusicPlayer
{
    SonglistItem::SonglistItem(param::hstring const& songName, param::hstring const& albumName, param::hstring const& coverPath) :
        SonglistItem(make<DisenchantMusicPlayer::implementation::SonglistItem>(songName, albumName, coverPath))
    {
    }
}
