// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_DisenchantMusicPlayer_StatisticPage()
{
    return winrt::detach_abi(winrt::make<winrt::DisenchantMusicPlayer::factory_implementation::StatisticPage>());
}
WINRT_EXPORT namespace winrt::DisenchantMusicPlayer
{
    StatisticPage::StatisticPage() :
        StatisticPage(make<DisenchantMusicPlayer::implementation::StatisticPage>())
    {
    }
}
