// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_Microsoft_UI_Input_1_H
#define WINRT_Microsoft_UI_Input_1_H
#include "winrt/impl/Microsoft.UI.Input.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Input
{
    struct __declspec(empty_bases) ICrossSlidingEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICrossSlidingEventArgs>
    {
        ICrossSlidingEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICrossSlidingEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDraggingEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDraggingEventArgs>
    {
        IDraggingEventArgs(std::nullptr_t = nullptr) noexcept {}
        IDraggingEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IGestureRecognizer :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGestureRecognizer>
    {
        IGestureRecognizer(std::nullptr_t = nullptr) noexcept {}
        IGestureRecognizer(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IHoldingEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IHoldingEventArgs>
    {
        IHoldingEventArgs(std::nullptr_t = nullptr) noexcept {}
        IHoldingEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputActivationListener :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputActivationListener>
    {
        IInputActivationListener(std::nullptr_t = nullptr) noexcept {}
        IInputActivationListener(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputActivationListenerActivationChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputActivationListenerActivationChangedEventArgs>
    {
        IInputActivationListenerActivationChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IInputActivationListenerActivationChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputActivationListenerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputActivationListenerStatics>
    {
        IInputActivationListenerStatics(std::nullptr_t = nullptr) noexcept {}
        IInputActivationListenerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputCursor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputCursor>
    {
        IInputCursor(std::nullptr_t = nullptr) noexcept {}
        IInputCursor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputCursorFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputCursorFactory>
    {
        IInputCursorFactory(std::nullptr_t = nullptr) noexcept {}
        IInputCursorFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputCursorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputCursorStatics>
    {
        IInputCursorStatics(std::nullptr_t = nullptr) noexcept {}
        IInputCursorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputCustomCursor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputCustomCursor>
    {
        IInputCustomCursor(std::nullptr_t = nullptr) noexcept {}
        IInputCustomCursor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputCustomCursorFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputCustomCursorFactory>
    {
        IInputCustomCursorFactory(std::nullptr_t = nullptr) noexcept {}
        IInputCustomCursorFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputDesktopNamedResourceCursor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputDesktopNamedResourceCursor>
    {
        IInputDesktopNamedResourceCursor(std::nullptr_t = nullptr) noexcept {}
        IInputDesktopNamedResourceCursor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputDesktopNamedResourceCursorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputDesktopNamedResourceCursorStatics>
    {
        IInputDesktopNamedResourceCursorStatics(std::nullptr_t = nullptr) noexcept {}
        IInputDesktopNamedResourceCursorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputDesktopResourceCursor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputDesktopResourceCursor>
    {
        IInputDesktopResourceCursor(std::nullptr_t = nullptr) noexcept {}
        IInputDesktopResourceCursor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputDesktopResourceCursorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputDesktopResourceCursorStatics>
    {
        IInputDesktopResourceCursorStatics(std::nullptr_t = nullptr) noexcept {}
        IInputDesktopResourceCursorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputKeyboardSource :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputKeyboardSource>
    {
        IInputKeyboardSource(std::nullptr_t = nullptr) noexcept {}
        IInputKeyboardSource(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputKeyboardSourceStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputKeyboardSourceStatics>
    {
        IInputKeyboardSourceStatics(std::nullptr_t = nullptr) noexcept {}
        IInputKeyboardSourceStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputLightDismissAction :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputLightDismissAction>
    {
        IInputLightDismissAction(std::nullptr_t = nullptr) noexcept {}
        IInputLightDismissAction(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputLightDismissActionStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputLightDismissActionStatics>
    {
        IInputLightDismissActionStatics(std::nullptr_t = nullptr) noexcept {}
        IInputLightDismissActionStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputLightDismissEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputLightDismissEventArgs>
    {
        IInputLightDismissEventArgs(std::nullptr_t = nullptr) noexcept {}
        IInputLightDismissEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputObject :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputObject>
    {
        IInputObject(std::nullptr_t = nullptr) noexcept {}
        IInputObject(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputObjectFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputObjectFactory>
    {
        IInputObjectFactory(std::nullptr_t = nullptr) noexcept {}
        IInputObjectFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputPointerSource :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputPointerSource>
    {
        IInputPointerSource(std::nullptr_t = nullptr) noexcept {}
        IInputPointerSource(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputSystemCursor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputSystemCursor>
    {
        IInputSystemCursor(std::nullptr_t = nullptr) noexcept {}
        IInputSystemCursor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputSystemCursorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputSystemCursorStatics>
    {
        IInputSystemCursorStatics(std::nullptr_t = nullptr) noexcept {}
        IInputSystemCursorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IManipulationCompletedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IManipulationCompletedEventArgs>
    {
        IManipulationCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IManipulationCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IManipulationInertiaStartingEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IManipulationInertiaStartingEventArgs>
    {
        IManipulationInertiaStartingEventArgs(std::nullptr_t = nullptr) noexcept {}
        IManipulationInertiaStartingEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IManipulationStartedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IManipulationStartedEventArgs>
    {
        IManipulationStartedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IManipulationStartedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IManipulationUpdatedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IManipulationUpdatedEventArgs>
    {
        IManipulationUpdatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IManipulationUpdatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMouseWheelParameters :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMouseWheelParameters>
    {
        IMouseWheelParameters(std::nullptr_t = nullptr) noexcept {}
        IMouseWheelParameters(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPointerEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPointerEventArgs>
    {
        IPointerEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPointerEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPointerPoint :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPointerPoint>
    {
        IPointerPoint(std::nullptr_t = nullptr) noexcept {}
        IPointerPoint(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPointerPointProperties :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPointerPointProperties>
    {
        IPointerPointProperties(std::nullptr_t = nullptr) noexcept {}
        IPointerPointProperties(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPointerPointTransform :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPointerPointTransform>
    {
        IPointerPointTransform(std::nullptr_t = nullptr) noexcept {}
        IPointerPointTransform(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPointerPredictor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPointerPredictor>
    {
        IPointerPredictor(std::nullptr_t = nullptr) noexcept {}
        IPointerPredictor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPointerPredictorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPointerPredictorStatics>
    {
        IPointerPredictorStatics(std::nullptr_t = nullptr) noexcept {}
        IPointerPredictorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IRightTappedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRightTappedEventArgs>
    {
        IRightTappedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IRightTappedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITappedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITappedEventArgs>
    {
        ITappedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ITappedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
