// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_Microsoft_Windows_Widgets_Providers_1_H
#define WINRT_Microsoft_Windows_Widgets_Providers_1_H
#include "winrt/impl/Microsoft.Windows.Widgets.Providers.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Windows::Widgets::Providers
{
    struct __declspec(empty_bases) IWidgetActionInvokedArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetActionInvokedArgs>
    {
        IWidgetActionInvokedArgs(std::nullptr_t = nullptr) noexcept {}
        IWidgetActionInvokedArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetContext :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetContext>
    {
        IWidgetContext(std::nullptr_t = nullptr) noexcept {}
        IWidgetContext(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetContextChangedArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetContextChangedArgs>
    {
        IWidgetContextChangedArgs(std::nullptr_t = nullptr) noexcept {}
        IWidgetContextChangedArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetInfo>
    {
        IWidgetInfo(std::nullptr_t = nullptr) noexcept {}
        IWidgetInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetManager>
    {
        IWidgetManager(std::nullptr_t = nullptr) noexcept {}
        IWidgetManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetManagerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetManagerStatics>
    {
        IWidgetManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IWidgetManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetProvider>
    {
        IWidgetProvider(std::nullptr_t = nullptr) noexcept {}
        IWidgetProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetUpdateRequestOptions :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetUpdateRequestOptions>
    {
        IWidgetUpdateRequestOptions(std::nullptr_t = nullptr) noexcept {}
        IWidgetUpdateRequestOptions(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetUpdateRequestOptionsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetUpdateRequestOptionsFactory>
    {
        IWidgetUpdateRequestOptionsFactory(std::nullptr_t = nullptr) noexcept {}
        IWidgetUpdateRequestOptionsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWidgetUpdateRequestOptionsStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWidgetUpdateRequestOptionsStatics>
    {
        IWidgetUpdateRequestOptionsStatics(std::nullptr_t = nullptr) noexcept {}
        IWidgetUpdateRequestOptionsStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
